In [2]:
import numpy as np
# nnumpy 常用方法

array(['123', '456', '789'],
      dtype='<U3')

In [59]:
# 1、从txt文件读取数据
np.genfromtxt('data/test.txt', delimiter=',', dtype=str)

array(['123', '456', '789'],
      dtype='<U3')

In [12]:
# 2、生成数据
a = np.array([1,2,3,4])
print(a)
b = np.random.random((4,5))
print(b)
c = np.zeros(5)
print(c)
d = np.ones((2,2))
print(d)
e = np.arange(4)
print(e)
f = np.arange(4,10)
print(f)
g = np.arange(1,100, 5)
print(g)
h = np.linspace(1, 20, 3)
print(h)

[1 2 3 4]
[[ 0.79258283  0.77876931  0.78907352  0.49831839  0.37916779]
 [ 0.14774699  0.57109916  0.41302873  0.82216068  0.73016182]
 [ 0.59071171  0.86251568  0.14737904  0.06789368  0.54388709]
 [ 0.01043839  0.40587522  0.53054519  0.73748838  0.79023051]]
[ 0.  0.  0.  0.  0.]
[[ 1.  1.]
 [ 1.  1.]]
[0 1 2 3]
[4 5 6 7 8 9]
[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
[  1.   10.5  20. ]


In [27]:
# 3、属性，包括类型、数组及矩阵大小
a = np.random.random(10)
b = np.random.random((4,5))
print(a.shape)
print(b.shape)
print(a.dtype)
print(b.dtype)
print(a.size)
print(b.size)

(10,)
(4, 5)
float64
float64
10
20


In [58]:
# 4、转换
a = np.random.random((4,5))
b = np.random.random((4,5))
print(a)
print(b)
print(a.reshape(20,1))
b.shape = (1,20)
print(b)
c = np.arange(4).reshape((2,2))
d = np.arange(4,8).reshape((2,2))
print(c)
print(d)
print(c.ravel())
print(np.vstack((c,d)))
print(np.hstack((c,d)))
print(np.vsplit(a, 2))
e = np.random.random((2,2)) * 10
print(e)
e.dtype = np.int
print(e)
f = np.random.random((2,2)) * 10
print(f)
g = np.floor(f)
print(g)

[[ 0.60795141  0.27532118  0.62325807  0.49508711  0.6741002 ]
 [ 0.38806056  0.49411044  0.83392464  0.05026023  0.78700123]
 [ 0.2414485   0.57566924  0.12582893  0.6081079   0.61390863]
 [ 0.38709078  0.67006486  0.39963671  0.82075543  0.35533404]]
[[ 0.33982807  0.76928459  0.78817744  0.78020245  0.70275504]
 [ 0.32587557  0.31739967  0.26405809  0.57962497  0.79001261]
 [ 0.07210728  0.07813884  0.20529021  0.25768324  0.71593685]
 [ 0.66675245  0.51480186  0.63907676  0.99244989  0.62012087]]
[[ 0.60795141]
 [ 0.27532118]
 [ 0.62325807]
 [ 0.49508711]
 [ 0.6741002 ]
 [ 0.38806056]
 [ 0.49411044]
 [ 0.83392464]
 [ 0.05026023]
 [ 0.78700123]
 [ 0.2414485 ]
 [ 0.57566924]
 [ 0.12582893]
 [ 0.6081079 ]
 [ 0.61390863]
 [ 0.38709078]
 [ 0.67006486]
 [ 0.39963671]
 [ 0.82075543]
 [ 0.35533404]]
[[ 0.33982807  0.76928459  0.78817744  0.78020245  0.70275504  0.32587557
   0.31739967  0.26405809  0.57962497  0.79001261  0.07210728  0.07813884
   0.20529021  0.25768324  0.71593685  0.6667

In [49]:
# 5、运算，注意matrix的内积与matrix乘法，注意numpy中的广播
a = np.arange(16).reshape(4,4)
b = np.arange(16, 32).reshape(4,4)
print(a)
print(b)
c = a * b
d = a.dot(b)
e = a - b
f = a + b
print(c)
print(d)
print(e)
print(f)
print(np.sin(f))
print(np.sum(e))
print(np.max(c, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[  0  17  36  57]
 [ 80 105 132 161]
 [192 225 260 297]
 [336 377 420 465]]
[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]
[[-16 -16 -16 -16]
 [-16 -16 -16 -16]
 [-16 -16 -16 -16]
 [-16 -16 -16 -16]]
[[16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
[[-0.28790332 -0.75098725  0.91294525 -0.00885131]
 [-0.90557836  0.76255845  0.27090579 -0.98803162]
 [ 0.55142668  0.52908269 -0.99177885  0.29636858]
 [ 0.74511316 -0.91652155  0.01770193  0.90178835]]
-256
[336 377 420 465]


In [52]:
# 6、比较机制
vector = np.arange(10)
print(vector)
print(vector>5)
print(vector[vector>5])
matrix = np.random.random(20).reshape((4,5))
print(matrix)
print(np.argmax(matrix, axis=0))

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[6 7 8 9]
[[ 0.4252416   0.77904921  0.37950253  0.53813832  0.10327586]
 [ 0.42933737  0.59237625  0.37412052  0.04072978  0.77106643]
 [ 0.81198995  0.72946255  0.81959864  0.32512144  0.21747319]
 [ 0.52278353  0.13447679  0.07852795  0.38046533  0.64162077]]
[2 0 2 0 1]
